package com.shermanconsulting.projecteuler;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 * @author sherman
 *
 */
public class Problem2 {

	/**
	 * Ease over elegance
	 * 
	 * @param args
	 */
	public static void main(String[] args) {
		final long max = 4_000_000l;
				
		long a = 1;
		long b = 2;
		long sum = 2;

		long next=0;
		while (next <= max) {
			next = a + b;
			if (next % 2 ==0) {
				sum += next;
			}
			a = b;
			b = next;
		}
		System.out.println(sum);

	}

}
